<?php require_once("./plantillas/layout/header.phtml"); ?>

<div class="container text-center">
  <div class="row align-items-center">
    
    <div class="col">
      <p class="alert alert-danger"><?= isset($mensaje) ? htmlspecialchars($mensaje, ENT_QUOTES, 'UTF-8') : '' ?></p>
    </div>
    
    <p>
      <a href="<?= isset($_SERVER['HTTP_REFERER']) ? htmlspecialchars($_SERVER['HTTP_REFERER'], ENT_QUOTES, 'UTF-8') : BASE_URL ?>">Volver</a>
    </p>
  </div>
</div>

<?php require_once("./plantillas/layout/footer.phtml"); ?>
