<!-- formulario de alta de genero -->
<form action="<?= ($genero !== null) ? "editarGenero/$genero->id" : 'nuevoGenero' ?>" method="POST" class="my-4" enctype="multipart/form-data">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input required name="nombre" id="nombre" type="text" class="form-control" value="<?= isset($genero) ? htmlspecialchars($genero->nombre, ENT_QUOTES, 'UTF-8') : '' ?>">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label for="fotos"><?= ($genero !== null && isset($genero->ruta_imagen) && $genero->ruta_imagen !== null) ? 'Cambiar' : 'Seleccionar' ?> Imagen</label>
                <input type="file" name="foto" id="fotos" accept=".png, .jpg, .jpeg">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label for="descripcion">Descripción</label>
        <textarea name="descripcion" id="descripcion" class="form-control" rows="3"><?= isset($genero) ? htmlspecialchars($genero->descripcion, ENT_QUOTES, 'UTF-8') : '' ?></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>
