<?php require 'plantillas/layout/header.phtml'; ?>
<div class="row gap-3">

    <ul class="list-group">
        <?php foreach ($generos as $genero): ?>
            <li class="list-group-item">
                <a href="generos/<?= htmlspecialchars($genero->id, ENT_QUOTES, 'UTF-8') ?>">
                    <?= htmlspecialchars($genero->nombre, ENT_QUOTES, 'UTF-8') ?> >
                </a>
            </li>
        <?php endforeach; ?>
    </ul>

    <p class="mt-3">
        <small>Mostrando <?= isset($count) ? $count : 0 ?> <?= ($count === 1) ? 'género' : 'géneros' ?><p class="mt-3">
            </p></small>
    </p>

    <?php if ($this->user): ?>
        <button><a href="agregarGenero">Agregar</a></button>
    <?php endif ?>
</div>
<?php require 'plantillas/layout/footer.phtml'; ?>