<?php require 'plantillas/layout/header.phtml' ?>


<ul class="list-group">
<?php foreach($generos as $genero): ?>
    <a href="generos/<?=$genero->id ?> "><li> <?= $genero->nombre ?>  > </li></a>
<?php endforeach ?>
</ul>
<p class="mt-3"><small>Mostrando <?=$count?> generos</small></p>


<?php if($this->user): ?>
        <button><a href="agregarGenero" class='btn btn-success btn-sm ml-auto'>Agregar</a></button>
    <?php endif ?>
<?php require 'plantillas/layout/footer.phtml' ?>
