<!DOCTYPE html>
<html lang="en">
<head>
    <title>Biblioteca</title>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/main.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    
<div class="navbar navbar-expand-lg bg-body-tertiary">
    
    <div class="container-fluid">
        <h1>Biblioteca</h1>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a href="libros" class="nav-link">Inicio</a></li>
                <li class="nav-item"><a href="listar/generos" class="nav-link">Generos</a></li>
                    <?php if(!$this->user): ?>
                        <li class="nav-item"><a href="showLogin" class="nav-link">Login</a></li>
                    <?php endif ?>
                    <?php if($this->user): ?>
                        <li class="nav-item"><a href="logout" class="nav-link">Logout</a></li>
                    <?php endif ?>
            </ul>
        </div>
    </div>

        <!-- Como en 'home' lo llamamos desde la vista de libros, tiene acceso a la variable 
         usuario y saludo -->
</div>

<div class="container">
    
