<?php require_once './plantillas/layout/header.phtml'?>
<?php if($mensaje != null): ?>
<p class="alert"><?=$mensaje?></p>
<p><a href="libros">volver</a></p>
<?php endif ?>



<form action="validarEditar/<?= $libro->id_libro ?>" method="post">

    <div class="mb-3">
        <input type="text" name="titulo" placeholder="titulo" value="<?= $libro->titulo?>">
        </input>
    </div>

    <div class="mb-3">    
        <input type="text" name="autor" placeholder="autor" value="<?= $libro->autor?>">
    </div>
    <div class="mb-3">    
        <select name="genero" id="genero">
        <?php foreach($listaGeneros as $genero):?>
            <option value="<?=$genero->nombre?>"><?= $genero->nombre ?></option>
        <?php endforeach?>
        </select>
    </div>
    
    <div class="mb-3">
        <input type="number" name="paginas" placeholder="cantidad de páginas" value="<?= $libro->paginas?>">
    </div>
    <div class="mb-3">
        <input type="text" name="cover" placeholder="(opcional) imagen" value="<?= $libro->cover?>">
        
    </div>
    <button type="submit" class="btn btn-primary">Editar</button>
</form>


<?php require_once './plantillas/layout/footer.phtml'?>
