<?php require_once './plantillas/layout/header.phtml'?>

<?php if($mensaje != null): ?>
<p class="alert alert-success"><?=$mensaje?></p>
<p><a href="libros">volver</a></p>
<?php endif ?>

<form action="confirmarAgregar" method="post">

    <div class="mb-3"><input type="text" name="titulo" placeholder="titulo"></div>

    
    <div class="mb-3">    
        <input type="text" name="autor" placeholder="autor">
    </div>
    
    <div class="mb-3">    
        <select name="genero" id="genero">
           
            <?php foreach($listaGeneros as $genero):?>
                <option value="<?=$genero->nombre?>"><?= $genero->nombre ?></option>
            <?php endforeach?>
        </select>
    </div>
    
     <div class="mb-3">
        <input type="number" name="paginas" placeholder="cantidad de páginas">
    </div>
    <div class="mb-3">
        <input type="text" name="cover" placeholder="(opcional) imagen">
        
    </div>
    <button type="submit" class="btn btn-primary">Agregar</button>
</form>


<?php require_once './plantillas/layout/footer.phtml'?>

