<?php require_once './plantillas/layout/header.phtml'?>
<?php if($mensaje != null): ?>
<p><?=$mensaje?></p>
<?php endif ?>



<form action="<?= BASE_URL ?>editar/<?= $id ?>" method="post">

    <div class="mb-3">
        <input type="text" name="titulo" placeholder="titulo" value="<?= $libro->titulo?>">
        </input>
    </div>

    <div class="mb-3">    
        <input type="text" name="autor" placeholder="autor" value="<?= $libro->autor?>">
    </div>
    <input type="text" name="genero" placeholder="nombre de genero" value="<?= $genero ?>">
    <div class="mb-3">
        <input type="number" name="paginas" placeholder="cantidad de páginas" value="<?= $libro->paginas?>">
    </div>
    <div class="mb-3">
        <input type="text" name="cover" placeholder="(opcional) imagen" value="<?= $libro->cover?>">
        
    </div>
    <button type="submit" class="btn btn-primary">Agregar</button>
</form>


<?php require_once './plantillas/layout/footer.phtml'?>
