<?php require_once './plantillas/layout/header.phtml'?>

<form action="validarEditar/<?= htmlspecialchars($libro->id_libro, ENT_QUOTES, 'UTF-8') ?>" method="post">

    <div class="mb-3">
        <input type="text" name="titulo" placeholder="titulo" value="<?= htmlspecialchars($libro->titulo, ENT_QUOTES, 'UTF-8') ?>">
    </div>

    <div class="mb-3">    
        <input type="text" name="autor" placeholder="autor" value="<?= htmlspecialchars($libro->autor, ENT_QUOTES, 'UTF-8') ?>">
    </div>
    
    <div class="mb-3">    
        <select name="genero" id="genero">
        <?php foreach($listaGeneros as $genero): ?>
            <option value="<?= htmlspecialchars($genero->nombre, ENT_QUOTES, 'UTF-8') ?>" <?= $genero->nombre === $libro->genero ? 'selected' : '' ?>><?= htmlspecialchars($genero->nombre, ENT_QUOTES, 'UTF-8') ?></option>
        <?php endforeach ?>
        </select>
    </div>
    
    <div class="mb-3">
        <input type="number" name="paginas" placeholder="cantidad de páginas" value="<?= htmlspecialchars($libro->paginas, ENT_QUOTES, 'UTF-8') ?>">
    </div>
    
    <div class="mb-3">
        <input type="text" name="cover" placeholder="(opcional) imagen" value="<?= htmlspecialchars($libro->cover, ENT_QUOTES, 'UTF-8') ?>">
    </div>
    
    <button type="submit" class="btn btn-primary">Editar</button>
</form>

<?php require_once './plantillas/layout/footer.phtml'?>
