<?php require_once './plantillas/layout/header.phtml'?>

<?php if($mensaje != null): ?>
<p class="alert alert-success"><?= htmlspecialchars($mensaje, ENT_QUOTES, 'UTF-8') ?></p>
<p><a href="libros">volver</a></p>
<?php endif ?>

<form action="confirmarAgregar" method="post">

    <div class="mb-3"><input type="text" name="titulo" placeholder="titulo" value="<?= isset($titulo) ? htmlspecialchars($titulo, ENT_QUOTES, 'UTF-8') : '' ?>"></div>

    <div class="mb-3">    
        <input type="text" name="autor" placeholder="autor" value="<?= isset($autor) ? htmlspecialchars($autor, ENT_QUOTES, 'UTF-8') : '' ?>">
    </div>
    
    <div class="mb-3">    
        <select name="genero" id="genero">
            <?php foreach($listaGeneros as $genero): ?>
                <option value="<?= htmlspecialchars($genero->nombre, ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars($genero->nombre, ENT_QUOTES, 'UTF-8') ?></option>
            <?php endforeach ?>
        </select>
    </div>
    
    <div class="mb-3">
        <input type="number" name="paginas" placeholder="cantidad de páginas" value="<?= isset($paginas) ? htmlspecialchars($paginas, ENT_QUOTES, 'UTF-8') : '' ?>">
    </div>
    
    <div class="mb-3">
        <input type="text" name="cover" placeholder="(opcional) imagen" value="<?= isset($cover) ? htmlspecialchars($cover, ENT_QUOTES, 'UTF-8') : '' ?>">
    </div>
    
    <button type="submit" class="btn btn-primary">Agregar</button>
</form>

<?php require_once './plantillas/layout/footer.phtml'?>
