<?php require_once './plantillas/layout/header.phtml' ?>

<div class="card" style="width: 18rem;">
    <?php if($libro->cover != ""): ?>
        <div class="img-container">
            <img src="<?= htmlspecialchars($libro->cover, ENT_QUOTES, 'UTF-8') ?>" class="card-img-top">
        </div>
    <?php else: ?>
        <div class="img-container">
            <img src="https://media.gettyimages.com/id/1901759032/es/vector/fuentes-educativas-dise%C3%B1o-universal-de-icono-de-l%C3%ADnea-simple-con-trazo-editable-adecuado.jpg?s=612x612&w=gi&k=20&c=WI_mWRXBCcNFhf7M4HFQt_lNs_YjxptyVFQHVlRwb-k=" class="card-img-top">
        </div>
    <?php endif ?>
    
    <div class="card-body">
        <h5 class="card-title">
            <?= htmlspecialchars($libro->titulo, ENT_QUOTES, 'UTF-8') ?>
        </h5>
        <p class="card-text">
            <?= htmlspecialchars($libro->autor, ENT_QUOTES, 'UTF-8') ?>
        </p>
        <p class="card-text">
            <?= htmlspecialchars($genero, ENT_QUOTES, 'UTF-8') ?>
        </p>
        
        <?php if($this->user): ?>
            <p><a href="eliminarLibro/<?= htmlspecialchars($libro->id_libro, ENT_QUOTES, 'UTF-8') ?>">Eliminar</a></p>
            <p><a href="editarLibro/<?= htmlspecialchars($libro->id_libro, ENT_QUOTES, 'UTF-8') ?>">Editar</a></p>
        <?php endif ?>   
    </div>
</div>

<?php require_once './plantillas/layout/footer.phtml' ?>
