<?php require_once("./plantillas/layout/header.phtml") ?>
<div class="row gap-3">


    <?php foreach ($libros as $libro): ?>
    
        <div class="card" style="width: 10rem;">
            <div class="img-container">
                <img src="https://media.gettyimages.com/id/1901759032/es/vector/fuentes-educativas-dise%C3%B1o-universal-de-icono-de-l%C3%ADnea-simple-con-trazo-editable-adecuado.jpg?s=612x612&w=gi&k=20&c=WI_mWRXBCcNFhf7M4HFQt_lNs_YjxptyVFQHVlRwb-k=" class="card-img-top">
            </div>
            <div class="card-body">
    
                <h5 class="card-title">
                    <?= $libro->titulo ?>
                </h5>
                <p class="card-text">
                    <?= $libro->autor ?>
                </p>
                <p class="card-text"><a href="libros/<?=$libro->id_libro?>">Ver detalles</a></p>
    
                <?php if($this->user): ?>
                    <p><a href="eliminarLibro/<?=$libro->id_libro?>">Eliminar</a></p>
                    <p><a href="editarLibro/<?=$libro->id_libro?>">Editar</a></p>
                <?php endif ?>
    
            </div>
    
        </div>
    
    <?php endforeach ?>

    <?php if($this->user): ?>
        <button><a href="agregarLibro">Agregar</a></button>
    <?php endif ?>

</div>
<?php require_once './plantillas/layout/footer.phtml' ?>
