<?php require_once './plantillas/layout/header.phtml'; ?>

<?php if (isset($mensaje) && $mensaje): ?>
    <div class='alert alert-danger' role='alert'>
        <?= htmlspecialchars($mensaje, ENT_QUOTES, 'UTF-8') ?>
    </div>
<?php endif ?>

<form method='post' action='validar'>
    <div class="mb-3">
        <label for='nombre'>Nombre</label>
        <input type='text' class='form-control' id='nombre' name='nombre' required>
    </div>
    <div class='mb-3'>
        <label for='password'>Password</label>
        <input type='password' class='form-control' id='password' name='password' required>
    </div>
    <button type='submit' class='btn btn-primary'>Login</button>
</form>

