<?php require 'templates/layout/header.phtml' ?>


<ul class="list-group">
<?php foreach($generos as $genero): ?>
    <a href="listar/generos/<?=$genero->id ?> "><li> <?php if($genero->ruta_imagen <> null) : ?> <img src="<?= $genero->ruta_imagen ?>" alt="">  <?php endif ?>    <?= $genero->nombre ?>  > </li></a>
<?php endforeach ?>
</ul>
<p class="mt-3"><small>Mostrando <?=$count?> generos</small></p>


<?php //if($this->user): ?>
        <button><a href="agregar/genero">Agregar</a></button>
    <?php //endif ?>
<?php require 'templates/layout/footer.phtml' ?>
